apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-js-test-pvc
  namespace: staging
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
